# Generated by Django 2.2.7 on 2019-11-27 16:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aggregator', '0002_auto_20191127_2321'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Article',
        ),
        migrations.AlterField(
            model_name='thread',
            name='phonograms',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
