
# Generated by Django 2.2.7 on 2019-11-27 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0003_auto_20191127_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aggregator.Thread'),
        ),
    ]
