# Generated by Django 2.2.7 on 2019-12-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0005_auto_20191205_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hash',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(blank=True, default=''),
        ),
    ]
