# Generated by Django 2.2.7 on 2019-12-05 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0006_auto_20191205_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='hash',
            new_name='phonograms_hash',
        ),
    ]
