# Generated by Django 2.2.7 on 2019-12-05 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0007_auto_20191205_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='phonograms_hash',
            new_name='hash',
        ),
    ]
