# Generated by Django 2.2.7 on 2019-12-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0008_auto_20191205_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hash',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
