# Generated by Django 2.2.7 on 2020-02-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0009_auto_20191205_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
