# Generated by Django 2.2.7 on 2020-02-23 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0010_article_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='hash',
            new_name='ph_hash',
        ),
    ]
